//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameLogicProtocol.proto
namespace Define.Socket
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"nPosition")]
  public partial class nPosition : global::ProtoBuf.IExtensible
  {
    public nPosition() {}
    
    private int _posX = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private int _posY = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"playerInfo")]
  public partial class playerInfo : global::ProtoBuf.IExtensible
  {
    public playerInfo() {}
    
    private int _kindId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"kindId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int kindId
    {
      get { return _kindId; }
      set { _kindId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _country = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string country
    {
      get { return _country; }
      set { _country = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _experience = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private int _maxHp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHp
    {
      get { return _maxHp; }
      set { _maxHp = value; }
    }
    private int _maxMp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxMp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxMp
    {
      get { return _maxMp; }
      set { _maxMp = value; }
    }
    private nPosition _pos = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public nPosition pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQHEART")]
  public partial class CMD_GAME_REQHEART : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQHEART() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPHEART")]
  public partial class CMD_GAME_RESPHEART : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPHEART() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQJOINROOM")]
  public partial class CMD_GAME_REQJOINROOM : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQJOINROOM() {}
    
    private ulong _roomid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPJOINROOM")]
  public partial class CMD_GAME_RESPJOINROOM : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPJOINROOM() {}
    
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQCREATEROOM")]
  public partial class CMD_GAME_REQCREATEROOM : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQCREATEROOM() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPCREATEROOM")]
  public partial class CMD_GAME_RESPCREATEROOM : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPCREATEROOM() {}
    
    private ulong _roomid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQPLAYERDATA")]
  public partial class CMD_GAME_REQPLAYERDATA : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQPLAYERDATA() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPPLAYERDATA")]
  public partial class CMD_GAME_RESPPLAYERDATA : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPPLAYERDATA() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private playerInfo _player = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public playerInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"STATE")]
    public enum STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=0)]
      NULL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAY", Value=1)]
      PLAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEAD", Value=2)]
      DEAD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOOKON", Value=3)]
      LOOKON = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQMOVE")]
  public partial class CMD_GAME_REQMOVE : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQMOVE() {}
    
    private nPosition _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public nPosition pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPMOVE")]
  public partial class CMD_GAME_RESPMOVE : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPMOVE() {}
    
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FLAG")]
    public enum FLAG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_REQRELINK")]
  public partial class CMD_GAME_REQRELINK : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_REQRELINK() {}
    
    private ulong _playerid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong playerid
    {
      get { return _playerid; }
      set { _playerid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GAME_RESPRELINK")]
  public partial class CMD_GAME_RESPRELINK : global::ProtoBuf.IExtensible
  {
    public CMD_GAME_RESPRELINK() {}
    
    private nPosition _pos = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public nPosition pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"FLAG")]
    public enum FLAG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAMEFINISH", Value=8)]
      GAMEFINISH = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}